version: "3.9"
services:
  redis0:
    image: "redis:alpine"
    command: redis-server --requirepass s3cr3tP@ssw0rd
    # ports:
    #   - "6379:6379" 
    networks:        
      local:
        ipv4_address: 10.0.0.2   
  app0:
    build: .  
    #image: localhost/sb
    networks:        
      local:
        ipv4_address: 10.0.0.3             
    # ports:
    #   - "8080:8080"
    volumes:
      - /home/v-user/Desktop/HighEdge/Straonit.HighEdge/Config/:/etc/secret-cluster/
    depends_on:
      - redis0
    environment:
      - REDIS_PASS=s3cr3tP@ssw0rd
      - NODE_UID=0
      - CLUSTER_CONFIG=/etc/secret-cluster/config.json
  
  redis1:
    image: "redis:alpine"
    command: redis-server --requirepass s3cr3tP@ssw0rd
    # ports:
    #   - "6379:6379"    
    networks:        
      local:
        ipv4_address: 10.0.0.4   
  app1:
    build: .    
    #image: localhost/sb
    networks:        
      local:
        ipv4_address: 10.0.0.5           
    # ports:
    #   - "8080:8080"
    volumes:
      - /home/v-user/Desktop/HighEdge/Straonit.HighEdge/Config/:/etc/secret-cluster/
    depends_on:
      - redis1
    environment:
      - REDIS_PASS=s3cr3tP@ssw0rd
      - NODE_UID=1
      - CLUSTER_CONFIG=/etc/secret-cluster/config.json

networks:
  local:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 10.0.0.0/24
            gateway: 10.0.0.1
          