version: "3.9"

networks:
  local:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 10.0.0.0/24
            gateway: 10.0.0.254

services:
  postgres:
    image: "postgres:14.2-alpine"   
    networks:        
      local:
        ipv4_address: 10.0.0.1   
    environment:
      - POSTGRES_DB=hackaton
      - POSTGRES_PASSWORD=s3cr3tP0stgr3s      
  redis0:
    image: "redis:alpine"
    command: redis-server --requirepass s3cr3tP@ssw0rd    
    networks:        
      local:
        ipv4_address: 10.0.0.2   
  app0:
    build: .      
    networks:        
      local:
        ipv4_address: 10.0.0.3           
    volumes:
      - /home/v-user/Desktop/HighEdge/Straonit.HighEdge/Config/:/etc/secret-cluster/
    depends_on:
      - postgres
      - redis0
    environment:
      - REDIS__PASS=s3cr3tP@ssw0rd
      - NODE_UID=0
      - LOCAL_IP=10.0.0.3
      - REDIS__HOST=10.0.0.2
      - REDIS__PORT=6379
      - CLUSTER_CONFIG=/etc/secret-cluster/config.json
      - POSTGRES_CONNECTION=Host=10.0.0.1;Username=postgres;Password=s3cr3tP0stgr3s;Database=hackaton
  
  redis1:
    image: "redis:alpine"
    command: redis-server --requirepass s3cr3tP@ssw0rd      
    networks:        
      local:
        ipv4_address: 10.0.0.4   
  app1:
    build: .        
    networks:        
      local:
        ipv4_address: 10.0.0.5              
    volumes:
      - /home/v-user/Desktop/HighEdge/Straonit.HighEdge/Config/:/etc/secret-cluster/
    depends_on:
      - postgres
      - redis1
    environment:
      - REDIS__PASS=s3cr3tP@ssw0rd
      - NODE_UID=1
      - LOCAL_IP=10.0.0.5
      - REDIS__HOST=10.0.0.4
      - REDIS__PORT=6379
      - CLUSTER_CONFIG=/etc/secret-cluster/config.json
      - POSTGRES_CONNECTION=Host=10.0.0.1;Username=postgres;Password=s3cr3tP0stgr3s;Database=hackaton

  redis2:
    image: "redis:alpine"
    command: redis-server --requirepass s3cr3tP@ssw0rd    
    networks:        
      local:
        ipv4_address: 10.0.0.6   
  app2:
    build: .        
    networks:        
      local:
        ipv4_address: 10.0.0.7           
    volumes:
      - /home/v-user/Desktop/HighEdge/Straonit.HighEdge/Config/:/etc/secret-cluster/
    depends_on:
      - postgres
      - redis1
    environment:
      - REDIS__PASS=s3cr3tP@ssw0rd
      - NODE_UID=1
      - LOCAL_IP=10.0.0.7
      - REDIS__HOST=10.0.0.6
      - REDIS__PORT=6379
      - CLUSTER_CONFIG=/etc/secret-cluster/config.json
      - POSTGRES_CONNECTION=Host=10.0.0.1;Username=postgres;Password=s3cr3tP0stgr3s;Database=hackaton

  redis3:
    image: "redis:alpine"
    command: redis-server --requirepass s3cr3tP@ssw0rd    
    networks:        
      local:
        ipv4_address: 10.0.0.8   
  app3:
    build: .        
    networks:        
      local:
        ipv4_address: 10.0.0.9         
    volumes:
      - /home/v-user/Desktop/HighEdge/Straonit.HighEdge/Config/:/etc/secret-cluster/
    depends_on:
      - redis1
    environment:
      - REDIS__PASS=s3cr3tP@ssw0rd
      - NODE_UID=1
      - LOCAL_IP=10.0.0.9
      - REDIS__HOST=10.0.0.8
      - REDIS__PORT=6379
      - CLUSTER_CONFIG=/etc/secret-cluster/config.json
      - POSTGRES_CONNECTION=Host=10.0.0.1;Username=postgres;Password=s3cr3tP0stgr3s;Database=hackaton
  
  redis4:
    image: "redis:alpine"
    command: redis-server --requirepass s3cr3tP@ssw0rd    
    networks:        
      local:
        ipv4_address: 10.0.0.10   
  app4:
    build: .        
    networks:        
      local:
        ipv4_address: 10.0.0.11         
    volumes:
      - /home/v-user/Desktop/HighEdge/Straonit.HighEdge/Config/:/etc/secret-cluster/
    depends_on:
      - redis1
    environment:
      - REDIS__PASS=s3cr3tP@ssw0rd
      - NODE_UID=1
      - LOCAL_IP=10.0.0.11
      - REDIS__HOST=10.0.0.10
      - REDIS__PORT=6379
      - CLUSTER_CONFIG=/etc/secret-cluster/config.json
      - POSTGRES_CONNECTION=Host=10.0.0.1;Username=postgres;Password=s3cr3tP0stgr3s;Database=hackaton

          